CREATE TABLE IF NOT EXISTS "crm_receivable_plan" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "period" bigint NOT NULL,
    "customer_id" bigint NOT NULL,
    "contract_id" bigint NOT NULL,
    "owner_user_id" bigint DEFAULT NULL,
    "receivable_id" bigint DEFAULT NULL,
    "return_time" timestamp DEFAULT NULL,
    "return_type" tinyint DEFAULT NULL,
    "price" decimal(24,6) NOT NULL,
    "remind_days" bigint DEFAULT NULL,
    "remind_time" timestamp DEFAULT NULL,
    "status" tinyint DEFAULT NULL,
    "percent" decimal(24,6) DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_contract" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(100) NOT NULL DEFAULT '',
    "name" varchar(100) NOT NULL DEFAULT '',
    "customer_id" bigint NOT NULL,
    "business_id" bigint DEFAULT NULL,
    "total_price" decimal(24,6) DEFAULT NULL,
    "discount_percent" decimal(24,6) DEFAULT NULL,
    "product_total_price" decimal(24,6) DEFAULT NULL,
    "order_date" timestamp DEFAULT NULL,
    "start_time" timestamp DEFAULT NULL,
    "end_time" timestamp DEFAULT NULL,
    "owner_user_id" bigint DEFAULT NULL,
    "audit_status" tinyint NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "sign_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_customer" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL DEFAULT '',
    "owner_user_id" bigint DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_receivable" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(100) NOT NULL,
    "plan_id" bigint DEFAULT NULL,
    "customer_id" bigint NOT NULL,
    "contract_id" bigint NOT NULL,
    "owner_user_id" bigint DEFAULT NULL,
    "audit_status" tinyint NOT NULL,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "return_time" timestamp DEFAULT NULL,
    "return_type" int DEFAULT NULL,
    "price" decimal(24,6) NOT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_permission" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "biz_type" int NOT NULL,
    "biz_id" bigint NOT NULL,
    "level" int NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
