-- CRM 报价单主表
CREATE TABLE IF NOT EXISTS `crm_quotation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '报价单ID',
  `quotation_no` varchar(64) NOT NULL COMMENT '报价单编号',
  `business_id` bigint DEFAULT NULL COMMENT '关联商机ID',
  `customer_id` bigint DEFAULT NULL COMMENT '关联客户ID',
  `contact_id` bigint DEFAULT NULL COMMENT '关联联系人ID',
  `owner_user_id` bigint NOT NULL COMMENT '负责人用户ID',
  `total_amount` decimal(12,2) DEFAULT 0.00 COMMENT '报价总金额',
  `discount_percent` decimal(5,2) DEFAULT 100.00 COMMENT '折扣百分比',
  `final_amount` decimal(12,2) DEFAULT 0.00 COMMENT '折后金额',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0草稿 1待审批 2已通过 3已拒绝 4已作废',
  `valid_days` int DEFAULT 30 COMMENT '有效天数',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `audit_user_id` bigint DEFAULT NULL COMMENT '审批人用户ID',
  `audit_time` datetime DEFAULT NULL COMMENT '审批时间',
  `audit_remark` varchar(512) DEFAULT NULL COMMENT '审批备注',
  `remark` varchar(1024) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quotation_no` (`quotation_no`),
  KEY `idx_business_id` (`business_id`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_owner_user_id` (`owner_user_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM 报价单';

-- CRM 报价单明细表
CREATE TABLE IF NOT EXISTS `crm_quotation_product` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '明细ID',
  `quotation_id` bigint NOT NULL COMMENT '报价单ID',
  `product_id` bigint NOT NULL COMMENT '产品ID',
  `product_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
  `product_code` varchar(64) DEFAULT NULL COMMENT '产品编号',
  `product_price` decimal(12,2) DEFAULT NULL COMMENT '产品原价',
  `quotation_price` decimal(12,2) NOT NULL COMMENT '报价价格',
  `count` decimal(12,2) NOT NULL DEFAULT 1.00 COMMENT '数量',
  `total_price` decimal(12,2) DEFAULT 0.00 COMMENT '小计',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_quotation_id` (`quotation_id`),
  KEY `idx_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM 报价单明细';
