CREATE TABLE IF NOT EXISTS "crm_order" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(64) NOT NULL DEFAULT '',
    "name" varchar(100) NOT NULL DEFAULT '',
    "customer_id" bigint DEFAULT NULL,
    "business_id" bigint DEFAULT NULL,
    "order_date" timestamp DEFAULT NULL,
    "owner_user_id" bigint DEFAULT NULL,
    "process_instance_id" varchar(64) DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "total_product_price" decimal(24,6) DEFAULT 0,
    "discount_percent" decimal(24,6) DEFAULT 0,
    "total_price" decimal(24,6) DEFAULT 0,
    "remark" varchar(500) DEFAULT '',
    "contact_last_time" timestamp DEFAULT NULL,
    "contact_next_time" timestamp DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT 'CRM订单表';

CREATE TABLE IF NOT EXISTS "crm_order_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "product_price" decimal(24,6) NOT NULL,
    "order_price" decimal(24,6) NOT NULL,
    "count" decimal(24,6) NOT NULL,
    "total_price" decimal(24,6) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT 'CRM订单产品关联表';
