CREATE TABLE IF NOT EXISTS "oa_leave" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "type" tinyint NOT NULL,
    "reason" varchar(500) DEFAULT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp NOT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_trip" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "type" tinyint DEFAULT NULL,
    "destination" varchar(200) DEFAULT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp NOT NULL,
    "reason" varchar(500) DEFAULT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_loan" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "purpose" tinyint DEFAULT NULL,
    "amount" bigint NOT NULL,
    "expected_repay_time" timestamp DEFAULT NULL,
    "reason" varchar(500) DEFAULT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_visit" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "customer_id" bigint DEFAULT NULL,
    "contact_person" varchar(50) DEFAULT NULL,
    "contact_phone" varchar(20) DEFAULT NULL,
    "visit_time" timestamp DEFAULT NULL,
    "location" varchar(200) DEFAULT NULL,
    "purpose" varchar(500) DEFAULT NULL,
    "notes" varchar(500) DEFAULT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_request" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "title" varchar(200) NOT NULL,
    "content" text DEFAULT NULL,
    "urgency" tinyint DEFAULT 1,
    "status" tinyint NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_report" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "type" varchar(50) NOT NULL,
    "report_date" date NOT NULL,
    "content" text DEFAULT NULL,
    "plan" text DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_schedule" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "title" varchar(200) NOT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp NOT NULL,
    "all_day" bit NOT NULL DEFAULT FALSE,
    "location" varchar(200) DEFAULT NULL,
    "description" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_task" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "title" varchar(200) NOT NULL,
    "description" text DEFAULT NULL,
    "assignee_id" bigint DEFAULT NULL,
    "priority" int DEFAULT 2,
    "status" int NOT NULL DEFAULT 1,
    "deadline" timestamp DEFAULT NULL,
    "completed_time" timestamp DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "oa_document" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "parent_id" bigint DEFAULT 0,
    "name" varchar(200) NOT NULL,
    "is_folder" bit NOT NULL DEFAULT FALSE,
    "file_id" bigint DEFAULT NULL,
    "file_url" varchar(500) DEFAULT NULL,
    "file_size" bigint DEFAULT NULL,
    "description" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
